"""Standalone review artifact with actual run results and all world tables."""
import base64,csv,html,json,statistics,sys,zipfile
from pathlib import Path
root=Path(__file__).resolve().parents[1];output=Path(sys.argv[1] if len(sys.argv)>1 else root.parent/'outputs');output.mkdir(parents=True,exist_ok=True)
w=json.loads((root/'research/world/world.json').read_text());analysis=json.loads((root/'research/world/analysis.json').read_text())
def table(rows):
 if not rows:return '<p>No completed results.</p>'
 cols=list(rows[0]);return '<div class="scroll"><table dir="ltr"><thead><tr>'+''.join('<th>'+html.escape(str(c))+'</th>' for c in cols)+'</tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+html.escape(f'{r.get(c):.5g}' if isinstance(r.get(c),float) else str(r.get(c,'')))+'</td>' for c in cols)+'</tr>' for r in rows)+'</tbody></table></div>'
def pic(path,caption):
 path=Path(path)
 return ('<figure><img alt="'+html.escape(caption)+'" src="data:image/png;base64,'+base64.b64encode(path.read_bytes()).decode()+'"><figcaption>'+html.escape(caption)+'</figcaption></figure>') if path.exists() else '<p>Figure not yet available.</p>'
parts=['''<!doctype html><html lang="he" dir="rtl"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Scheduling Simulation — Research review v0.4</title><style>body{font:17px/1.65 Arial,sans-serif;color:#203040;background:#f4f7fa;margin:0}main{max-width:1200px;margin:auto;padding:30px}h1{font-size:34px;line-height:1.3}h2{margin-top:38px}section,.card{background:white;padding:24px;border:1px solid #d7e0e8;border-radius:10px;margin:20px 0}.status{border-right:6px solid #b76b00;background:#fff6df;padding:18px}.scroll{overflow:auto;max-height:600px}table{border-collapse:collapse;width:100%;font:14px/1.5 Arial}th,td{padding:9px;border-bottom:1px solid #dce4ed;text-align:left;vertical-align:top}th{background:#163652;color:white;position:sticky;top:0}tr:nth-child(even){background:#f0f5f8}img{width:100%;height:auto}figcaption{font-size:14px;color:#526579}summary{cursor:pointer;font-weight:bold;padding:12px}code{direction:ltr;unicode-bidi:embed;font-size:15px}a{color:#075e91}@media print{details{display:block}.scroll{max-height:none;overflow:visible}section{break-inside:avoid}}</style><main><h1>Scheduling Simulation<br>מודל מכויל — גרסת מחקר 0.4</h1><p>הפרדת פעולות, משפחות מכונות ומכונות פיזיות; ביקוש חיצוני; תוצאות ניסוי בפועל.</p><div class="status"><b>סטטוס: המימוש נבדק, אך Baseline יציב עדיין לא אושר.</b><br>הדוח אינו מעניק אישור לגרסה על בסיס מעבר בדיקות תוכנה בלבד. בדיקת Replay חזותית לא הושלמה, וחלונות הכיול אינם מוכיחים עדיין התייצבות.</div>''']
parts+=['<section><h2>הממצאים שהובילו למודל</h2>'+table([{'Metric':'Source reports','Value':26222},{'Metric':'Retained jobs / items','Value':'343 / 164'},{'Metric':'Part families / operations','Value':'19 / 86'},{'Metric':'Physical machines / fixed processing entries','Value':'68 / 2,284'},{'Metric':'Quantity mean / median / maximum','Value':'2,397.71 / 475 / 50,300'},{'Metric':'Current joint-capacity candidate jobs/day','Value':w['demand']['baseline_jobs_per_day']}])+'<p>המסלולים והכמויות נגזרו מדיווחים. כמות העבודה היא אומדן מצטבר ולא גודל הזמנת לקוח מאומת. זמני התקן שימשו בסיס הנדסי לזמן מכונה, אך אינם מבודדים בוודאות את הזמן האוטומטי.</p>'+pic(root/'research/world/source_analysis.png','התפלגות הכמויות, ECDF וכיסוי דפוסי מסלול — ללא קיצוץ הזנב')+pic(root/'research/world/processing_source_evidence.png','זמני דיווח ותקן: יש להבחין בינם לבין זמן מכונה אוטומטי')+'</section>']
parts+=['<section><h2>מדוע קצב הבסיס השתנה</h2><p>חישוב לפי מכונות בלבד נתן 2.183 עבודות ביום. אבל העבודה הידנית הנדרשת היא 9,489.54 דקות לעבודה, מול 11,700 דקות עובד זמינות ביום לפני הליכה ושינוע. הקצב הזה מציע כ־177% עומס אנושי. הכמויות לא הוקטנו; מועמד הבסיס החדש, 0.9247 עבודות ביום, נותן 75% עומס ידני מחושב לפני הליכה ושינוע.</p><p>ארבעת עובדי ה־Setup כמעט אינם מנוצלים במועמד הנוכחי; לכן טרם הושג גם היעד של אילוץ Setup משמעותי. אין הצדקה לשנות את מספרם בתוך הריצה כדי להסתיר זאת.</p><p>זהו מועמד לכיול, לא אישור יציבות. הזמנות גדולות ללא פיצול עשויות להימשך חודשים, ולכן יש צורך בהפרדה בין סיום drain לבין התייצבות תוך כדי הגעות.</p></section>']
cal=[]
for p in sorted((root/'results/world-joint-calibration').glob('calibration_*.json')):
 d=json.loads(p.read_text());s=d['algorithms']['FIFO'];rr=d['raw_runs'];cal.append({'Arrival scale':d['arrival_load'],'Jobs/day':rr[0]['lambda_jobs_day'],'Replications':s['n'],'Mean flow days':s['mean']/1440 if s['mean'] is not None else None,'Mean WIP':s['mean_wip']['mean'],'WIP slope CI95 jobs/day':s['wip_slope']['ci95'],'Machine busy':statistics.mean(r['machine_utilization'] for r in rr),'Operator busy/on-duty':statistics.mean(r['worker_available_utilization'] for r in rr),'Setup busy/on-duty':statistics.mean(r['setup_worker_utilization'] for r in rr),'Throughput jobs/day':s['throughput']['mean'],'Status':s['status']})
parts+=['<section><h2>כיול משולב: מכונות ועובדים</h2><p>56 ימי פרה־הרצה ו־56 ימי מדידה; זמן השהייה של אוכלוסיית השחרור כולל drain. רווחי סמך מתייחסים לממוצעים בין רפליקציות. אי־זיהוי שיפוע חיובי אינו מוכיח יציבות.</p>'+table(cal)+'</section>']
surface_path=root/'results/world-v04-final-grid/surface.json';surface=json.loads(surface_path.read_text()) if surface_path.exists() else {'points':[]};gridrows=[]
for p in surface['points']:
 for a,s in p['algorithms'].items():gridrows.append({'Arrival scale':p['arrival_load'],'Quantity scale':p['batch_size'],'Algorithm':a,'n':s['n'],'Flow hours':s['mean']/60 if s['mean'] is not None else None,'CI95 minutes':s['ci95'],'Status':s['status']})
parts+=['<section><h2>משטח תגובה: ניסוי בפועל</h2><p><b>ניסוי זה משתמש במועמד המקורי המבוסס על מכונות: λ בסיסי 2.183 עבודות ביום.</b> לכן זו גם בדיקת עומס יתר, ואינה משטח של ה־Baseline הנוכחי. בכל תשע הנקודות רווח הסמך להפרש בין SPT ל־FIFO כולל אפס; לא הוכח יתרון אלגוריתמי. ציר X הוא קצב הגעה, Y הוא גודל עבודה ו־Z הוא זמן שהייה ממוצע. 7 ימי פרה־הרצה ו־7 ימי מדידה; אין לייחס למשטח משמעות של מצב יציב.</p>'+pic(root/'results/world-v04-final-grid/response_surface.png','משטח שנמדד ברפליקציות אמיתיות; פערים מציינים אוכלוסיות שלא הושלמו')+table(gridrows)+'</section>']
parts+=['<section><h2>תנועת עובדים מתוך לוג הסימולציה</h2><p>תמונה זו נוצרה מאירועי הריצה, לא מצילום הדפדפן. הקווים מציינים תנועה שנרשמה בפועל. היא אינה מחליפה בדיקת הממשק האינטראקטיבי.</p>'+pic(root/'results/world-joint-replay/replay_frame.png','רגע מתוך השחזור של המועמד המשולב')+'</section>']
parts+=['<section><h2>טבלאות העולם המלאות</h2><p>הטבלאות ניתנות לפתיחה ולגלילה, כולל כל 2,284 זמני העיבוד. משפחת מכונות יכולה לחזור כמה פעמים במסלול; כל שורה היא פעולה עצמאית.</p>']
for name,label in [('part_families','A. Part Families'),('operations','B. Operations / Setup Classes'),('machines','C. Physical Machines'),('processing_matrix','D. Processing Matrix'),('setup_matrices','E. Setup Matrices'),('quantities','F. Empirical Quantity Samples'),('route_coverage','G. Route Coverage'),('offered_load','H. Processing Capacity')]:
 with (root/'research/world'/f'{name}.csv').open() as f:rows=list(csv.DictReader(f))
 parts.append('<details><summary>'+label+f' — {len(rows):,} rows</summary>'+table(rows)+'</details>')
parts+=['<details><summary>I. Worker Resources</summary>'+table([{'Parameter':k,'Value':v} for k,v in w['resources'].items()])+'</details><details><summary>J. Parameter Provenance</summary>'+table([{'Parameter':k,'Interpretation':v} for k,v in w['provenance'].items()])+'</details></section>']
parts+=['''<section><h2>מה נבדק ומה נשאר פתוח</h2><p>59 בדיקות תוכנה עברו, ובהן בדיקות עצמאיות הכוללות: פעולות חוזרות באותה משפחה, setup על אותה מכונה, זמן מכונה קבוע, בעלות לפי פעולה והעברת אחריות, שחרור עובד בזמן עיבוד, שינוע ללא פיצול מנת ביצוע, בחירת מכונה מחדש לפי ECT, ביקוש זהה בין מדיניות, שמירת תוצאות Grid וטיפול באוכלוסיות שלא הושלמו.</p><p>החלופות וההנחות אינן שקולות לראיות מהמפעל: ארבעת עובדי setup, הכשירויות המאוגמות, שיוך המכונות למשפחות, מהירויות המכונה ומטריצות setup הם רכיבי עולם הנדסיים או סינתטיים. Rare families, זנב הכמויות, זמני המכונה ומשך הפרה־הרצה דורשים מחקר נוסף.</p><p>להרצה מקומית לאחר קבלת הקוד: <code>python run_factory.py</code>. בממשק ניתן לבחור Arrival Scale, Batch Size Scale, מספר רפליקציות וערכי Grid.</p></section></main></html>''']
(output/'Simulation_Research_Report_v04.html').write_text(''.join(parts))
# Persist raw research outputs, not repository code or private source workbook.
with zipfile.ZipFile(output/'Simulation_Raw_Experiments_v04.zip','w',zipfile.ZIP_DEFLATED) as z:
 for folder in ['world-v04-final-grid','world-joint-calibration','world-v04-final-calibration','world-joint-replay','world-calibration','world-grid']:
  for p in (root/'results'/folder).rglob('*'):
   if p.is_file():z.write(p,p.relative_to(root/'results'))
 z.writestr('README.txt','Current ECT grid: world-v04-final-grid, original machine-only arrival candidate 2.1830489787976326/day.\nJoint capacity calibration: world-joint-calibration, candidate 0.9247027030846621/day.\nOther folders are prior/partial pilots, not current acceptance evidence. Full raw runs preserve world/code hashes. No stationary baseline approved.\n')
print(output/'Simulation_Research_Report_v04.html');print(output/'Simulation_Raw_Experiments_v04.zip')
