"""Render the source/map/mix audit as an explanatory, self-contained discussion."""
from pathlib import Path
import json,base64,html
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle,Patch
root=Path(__file__).resolve().parents[1];out=root/'research/machine-mix-audit';d=json.loads((out/'audit.json').read_text());dest=root.parent/'outputs';dest.mkdir(exist_ok=True)
colors={'Milling':'#158e9d','Turning':'#cf7445','Honing':'#8565b2','WireEDM':'#5c824a','No reports':'#c5ccd4'}
fig,axes=plt.subplots(2,1,figsize=(14,10),layout='constrained')
for ax,key,title in zip(axes,['Reported process family','v04 synthetic family'],['A. Source report labels attached to existing map locations','B. v0.4 synthetic family allocation on the same locations']):
 for r in d['mapping']:
  ax.add_patch(Rectangle((r['x'],r['y']),80,70,facecolor=colors[r[key]],edgecolor='#536575',lw=.4));ax.text(r['x']+40,r['y']+35,r['Machine'],ha='center',va='center',fontsize=5.5)
 ax.axvline(1150,ls='--',color='#263b52');ax.set(xlim=(-40,2370),ylim=(840,-40),aspect='equal',xlabel='Relative map x-coordinate',ylabel='Relative map y-coordinate',title=title)
 ax.text(530,0,'Left floor: 40 locations',ha='center');ax.text(1730,0,'Right floor: 28 locations',ha='center')
axes[0].legend(handles=[Patch(color=c,label=f) for f,c in colors.items()],loc='upper center',bbox_to_anchor=(.5,1.22),ncol=5,fontsize=9)
fig.savefig(out/'map_source_vs_v04.png',dpi=160);plt.close(fig)
fig,ax=plt.subplots(figsize=(12,4.5),layout='constrained');rs=d['probabilities'];ix=list(range(len(rs)));width=.25
for j,(key,c) in enumerate([('Historical %','#158e9d'),('Uniform %','#8565b2'),('Mixed %','#cf7445')]):ax.bar([i+(j-1)*width for i in ix],[r[key] for r in rs],width=width,label=key,color=c)
ax.set_xticks(ix,[r['Family'] for r in rs],rotation=50);ax.set(ylabel='Arrival probability (%)',title='Same 19 families, three fixed demand mixes');ax.legend();fig.savefig(out/'mix_probabilities.png',dpi=160);plt.close(fig)
def table(rs):
 if not rs:return ''
 keys=list(rs[0]);fmt=lambda x:f'{x:,.2f}' if isinstance(x,float) else str(x)
 return '<div class="scroll"><table dir="ltr"><thead><tr>'+''.join('<th>'+html.escape(k)+'</th>' for k in keys)+'</tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+html.escape(fmt(r[k]))+'</td>' for k in keys)+'</tr>' for r in rs)+'</tbody></table></div>'
def pic(n,caption):return '<figure><img src="data:image/png;base64,'+base64.b64encode((out/(n+'.png')).read_bytes()).decode()+'"><figcaption>'+caption+'</figcaption></figure>'
source=d['source_machine_statistics'];simple=[{'Machine family':r['Family'],'Reported IDs':r['Reported station IDs'],'Share of 62 reported IDs %':100*r['Reported station IDs']/62,'In map':r['Reported IDs in map'],'Left':r['Mapped stations left'],'Right':r['Mapped stations right'],'Report share %':r['Report share %']} for r in source]
body='''<!doctype html><html lang="he" dir="rtl"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>מכונות ותמהיל — בסיס ההחלטה</title><style>body{font:17px/1.75 Arial;background:#f2f6fa;color:#203449;margin:0}main{max-width:1160px;margin:auto;padding:28px}section{background:white;padding:24px;border:1px solid #dbe3ec;margin:22px 0;border-radius:10px}.scroll{overflow:auto}table{border-collapse:collapse;width:100%;font-size:13px;line-height:1.5}td,th{padding:9px;border-bottom:1px solid #dbe3ec;text-align:left}th{background:#173d55;color:white}img{width:100%}figcaption{font-size:14px}.note{background:#fff2d8;padding:14px}details{margin:15px 0}summary{cursor:pointer;font-weight:bold}</style><main><h1>מכונות ותמהיל: מה ידוע, מה הוחלט ומה עדיין מוצע</h1><p>ניתוח בעקבות בקשתך להבין את בחירת סוגי המכונות, הקשר למפה ומשמעות תמהיל משפחות החלקים.</p><p class="note">Inspection הוסר מהתכנון הבא לפי בקשתך. אין צורך למלא את מקומו רק כדי לשמור על שש משפחות. הגרסה הפעילה נותרה v0.4; המסמך אינו טוען שהפריסה או התמהיל החדשים כבר מומשו.</p>'''
body+='<section><h2>1. הנתונים בפועל</h2><p>מקור: production_reports.xlsx. נבדקו 20,821 דיווחים של 344 הוראות ייצור ללא מספרים סידוריים. כאן נכללת גם ההוראה בעלת הכמות האפסית; ניתוח הביקוש בהמשך משתמש ב־343 הוראות בעלות כמות חיובית. מזהה מכונה נלקח מתחילת תווית התחנה; סוג הפעולה נלקח ממרכז העבודה. לא נמצא מזהה מכונה ששויך ליותר ממרכז עבודה אחד בקבוצה הזאת.</p>'+table(simple)+'<p>62 מזהים הופיעו בדיווחים. 58 מהם קיימים במפה, וארבעה אינם מופיעים בה. מתוך 68 מיקומי המפה, לעשרה לא נמצאו דיווחים. היעדר דיווח אינו מוכיח שהמכונה אינה קיימת, פנויה או מיותרת.</p><p>אחוז דיווחים אינו אחוז קיבולת: מכונה יכולה לייצר הרבה רשומות קצרות או מעט רשומות ארוכות. גם דקות עבודה מדווחות אינן בהכרח זמן מכונה אוטומטי. לכן אין להקצות 74% מהמכונות לכרסום רק משום שכ־74% מהדיווחים הם כרסום.</p></section>'
body+='<section><h2>2. מה הקשר בין המפה לבין v0.4</h2><p>נשמרו 68 מלבני מכונות, הקואורדינטות וגרף המסדרונות. מזהי המכונות הוחלפו ב־M01…M68. הסוגים הוקצו מחדש ל־44 Milling, 20 Turning, שתי Honing ושתי WireEDM. ההקצאה התבססה על עומס העיבוד הצפוי בקטלוג הישן, עם מינימום שתי מכונות לכל משפחה; המיקום של כל סוג נקבע לפי סדר מזהים ולא לפי תכנון מחלקות או תנועת חלקים.</p><p><b>24 מתוך 58 מיקומים שסוגם מזוהה בדיווחים קיבלו ב־v0.4 משפחה אחרת.</b> זהו שינוי סינתטי, לא שחזור המפעל. בנוסף, האחדת המחלקות ל־floor ביטלה את הפרדת העובדים בין הקומות. כך איבדנו גם הסבר הנדסי לפריסה וגם אילוץ תנועה חשוב.</p>'+pic('map_source_vs_v04','אותם מיקומים ומזהי v0.4 בשני האיורים. למעלה צבע לפי מרכז העבודה בדיווח המקור; למטה צבע לפי העולם הסינתטי. אפור מציין שאין דיווח תואם, לא מכונה פנויה.')+'<details><summary>מיפוי מלא של כל 68 המיקומים</summary>'+table(d['mapping'])+'</details><p>המלצתי: להשתמש במפה כפריסה התחלתית — בסיס כרסום משמאל ובסיס חריטה מימין — ולהציג כל שינוי סוג או מיקום במפורש. משפחת מכונות וקומה יישארו שני שדות נפרדים; יש שתי מכונות כרסום מזוהות גם בצד ימין. הקומה אינה קובעת את סוג המכונה.</p></section>'
body+='''<section><h2>3. מדוע הוצעו שש, ומה אני ממליץ עכשיו</h2><p>לא היה ניתוח שהוכיח ששש הוא המספר המתאים. ההצעה הורכבה משלושה סוגים שנצפו ישירות (Milling, Turning, WireEDM), הרחבה סינתטית מ־Honing ל־Grinding, ושתי תוספות (Finishing, Inspection). המטרה הייתה ליצור תחרות בין יכולות, פעולות גמר ונתיבי עיבוד מגוונים. זהו שיקול תכנון, לא תוצאת נתונים.</p><p>הרחבת Honing ל־Grinding לא הוצדקה באמצעות מידע על יכולות מכונות; אין בדאטה שלנו בסיס להניח שקיימת ביניהן התאמה מלאה. Inspection הוסר לבקשתך. גם Finishing צריך להיות מוגדר כמשפחת ציוד גימור ייעודי, ולא רק כשם לפעולת Finish שכבר יכולה להתבצע על Milling.</p><p><b>המלצתי המעודכנת היא לבחון חמש משפחות:</b> Milling, Turning, Honing, WireEDM ומשפחת ציוד גימור ייעודי סינתטית. ארבע הראשונות מספקות עוגן ברור; החמישית מוסיפה יכולת שהמסלולים יכולים להשתמש בה. אין צורך לשמר את נדירות Honing ו־WireEDM בתמהיל החדש. זו הצעה, לא שינוי שכבר הופעל.</p><p>לא אתן עכשיו מספר מכונות לכל משפחה כאילו חושב עבור העולם החדש. קודם יש להגדיר מסלולים, כמויות וזמני פעולה. לאחר מכן מחשבים דקות נדרשות לכל משפחה ולכל קומה, ומקצים מכונות מקבילות. היחס בין המספרים 44/20/2/2 אינו מחייב את העולם הבא.</p></section>'''
body+='<section><h2>4. האם תמהיל שווה הוא רעיון טוב? הנה השוואה מבוקרת</h2><p>נשמרו אותן 19 משפחות, אותן כמויות מותנות ואותם מסלולים. הוחלפו רק הסתברויות ההגעה: שכיחות היסטורית; אחידות; וממוצע 50/50 של השתיים. 50/50 הוא תרחיש המחשה, לא משקל אופטימלי שנמצא.</p>'+pic('mix_probabilities','שלוש אפשרויות קבועות מראש. אף אפשרות אינה מסתכלת על התורים או משנה ביקוש במהלך הריצה.')+table(d['mix_comparison'])+'<p>המדד “מספר משפחות אפקטיבי” הוא 1 חלקי סכום ריבועי ההסתברויות. הוא נותן תחושה של ריכוז: תמהיל של 19 משפחות יכול להיות מרוכז כמו כ־7 משפחות שוות הסתברות. הוא אינו מספר משפחות פיזי ואינו מדד יציבות. מספר המשפחות הצפוי ב־100 עבודות מחושב כסכום ההסתברויות שכל משפחה תופיע לפחות פעם אחת.</p><p><b>הממצא המרכזי:</b> אחידות מגדילה את מגוון המשפחות שמופיעות, אבל מעלה את מספר הפעולות הממוצע מ־2.84 ל־4.53, משום שהיא נותנת יותר משקל למסלולים הארוכים הנדירים. אם שומרים גם את הכמויות הישנות לפי משפחה, הממוצע עולה מכ־2,398 לכ־3,490 יחידות. לכן אחידות אינה בהכרח הקלה על המפעל.</p>'+table(d['machine_reach'])+'<p>לדוגמה, מספר ביקורי Turning לעבודה עולה מ־1.57 ל־2.74 תחת אחידות. חשוב לספור ביקורים חוזרים: שני שלבי Turning באותה עבודה דורשים שתי פעולות, גם אם נשלחו לאותה מכונה.</p><details><summary>הסתברויות לכל משפחה</summary>'+table(d['probabilities'])+'</details></section>'
body+='''<section><h2>5. החלטה מוצעת על בסיס הממצאים</h2><p>לא הייתי מפעיל תמהיל אחיד על הקטלוג הישן. תחילה נגדיר את קטלוג המסלולים החדש ללא Inspection, עם מספר פעולות מבוקר ותיאור מפורש של ציוד הגימור. לאחר מכן נשווה תמהיל אחיד ותמהיל מוטה וקבוע על אותו קטלוג, תוך שמירה על ממוצע הכמות הכולל ועל חלופת הריכוז שבודקים. עבור משפחות חדשות אין הסתברות היסטורית ישירה; כל חיבור לנתונים דורש מיפוי גלוי.</p><p>המכונות יוקצו לפי דקות עומס, לא לפי מספר עבודות או מספר רשומות. כל הקצאה תוצג יחד עם מיקומה בקומה, זכאות הפעולות וקיבולת השירות האנושי המקומית. כך יהיה אפשר לראות מראש היכן צפוי צוואר בקבוק, ולבדוק אותו בסימולציה.</p><p>השוואות התמהיל כאן הן חישובים אנליטיים, לא הרצות יציבות. אישור מעבר חלקים באמצעות העברה בין קומות נשמר; עובדים ומומחי Setup נשארים מקומיים. תיקון זה עדיין ממתין למימוש.</p></section></main></html>'''
(dest/'Simulation_Machines_and_Demand_Mix.html').write_text(body)
# Keep the rejected inspection proposal as historical evidence; write the current exclusion explicitly.
(out/'current_design_status.json').write_text(json.dumps({'status':'DISCUSSION_NOT_ACTIVE','inspection':'EXCLUDED_BY_USER','recommended_machine_families':['Milling','Turning','Honing','WireEDM','Dedicated Finishing'],'machine_counts':'NOT_YET_DESIGNED_FOR_NEW_ROUTES','mix':'NOT_SELECTED; old19 uniform is not adopted','floor_rules':'APPROVED: parts transfer via resource, workers stay local; implementation pending'},indent=2))
print(dest/'Simulation_Machines_and_Demand_Mix.html')
